# Site settings
# Accessed via {{ site.title }}, {{ site.email }}, and so on.
#
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gotham | A flexible web framework created in Rust
description: > # this means to ignore newlines until "baseurl:"
  A flexible web framework that promotes stability, safety, security and speed.
baseurl: "" 
url: "" 
pagintate: 10
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
